//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManage.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHDBan
    {
        public string MaHDBan { get; set; }
        public string MaHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual tblHDBan tblHDBan { get; set; }
        public virtual tblHang tblHang { get; set; }
    }
}
