//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManage.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHang()
        {
            this.tblChiTietHDBans = new HashSet<tblChiTietHDBan>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string MaChatLieu { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> DonGiaBan { get; set; }
        public string Anh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblChatLieu tblChatLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHDBan> tblChiTietHDBans { get; set; }
    }
}
