//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPtheoMaus = new HashSet<SPtheoMau>();
        }
        [Display(Name = "Mã Sản Phẩm")]
        public string MaSanPham { get; set; }
        [Display(Name = "Tên Sản Phẩm")]
        public string TenSanPham { get; set; }
        [Display(Name = "Phân Loại Chính")]
        public string MaPhanLoai { get; set; }
        [Display(Name = "Giá Nhập")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Giá nhập không hợp lệ!")]
        public Nullable<long> GiaNhap { get; set; }
        [Display(Name = "Đơn Giá Bán Nhỏ Nhất")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Giá nhập không hợp lệ!")]
        public Nullable<long> DonGiaBanNhoNhat { get; set; }
        [Display(Name = "Đơn Giá Bán Lớn Nhất")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Giá nhập không hợp lệ!")]
        public Nullable<long> DonGiaBanLonNhat { get; set; }
        [Display(Name = "Trạng Thái")]
        public Nullable<bool> TrangThai { get; set; }
        [Display(Name = "Mô Tả Ngắn")]
        public string MoTaNgan { get; set; }
        [Display(Name = "Ảnh Đại Diện")]
        [RegularExpression("^[a-zA-Z0-9]+\\.jpg$", ErrorMessage = "File ảnh không đúng định dạng.")]
        public string AnhDaiDien { get; set; }
        [Display(Name = "Nổi Bật")]
        public Nullable<bool> NoiBat { get; set; }
        [Display(Name = "Phân Loại Phụ")]
        public string MaPhanLoaiPhu { get; set; }
    
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPtheoMau> SPtheoMaus { get; set; }
    }
}
